7902698: Collision of zero timestamp as a special value with use in filesystems
openjdk/jtharness pull request #22
Opened 2022-01-20 03:27 UTC by cushon

This fixes a bug when the timestamp of a test file is set to zero, since jtharness currently uses zero as a special value. See discussion in [CODETOOLS-7902698](https://bugs.openjdk.java.net/browse/CODETOOLS-7902698).

2022-01-25 20:28 UTC, dbessono reviewed
It seems that previously zero default value served as "undefined yet" for these fields that are switched to "-1" as their default value. However 'URLConnection::getLastModified' returns "0 if not known" and 'File::lastModified' spec asserts: "returns 0L if the file does not exist or if an I/O error occurs. The value may be negative indicating the number of milliseconds before the epoch". 

It possibly would be more reliable and readable to switch types of these fields from 'long' to OptionalLong with OptionalLong.empty() as their default value.

2022-01-25 22:36 UTC, cushon commented
Thanks for the review!

> It possibly would be more reliable and readable to switch types of these fields from 'long' to OptionalLong with OptionalLong.empty() as their default value.

Done

2022-02-02 22:18 UTC, dbessono commented on src/com/sun/javatest/TRT_TreeNode.java
> +        if (lastScanDate.isEmpty() || lmd <= lastScanDate.getAsLong()) {
Seen a failure of com.sun.javatest.SelectionTest when checking the latest patch... It seems that here a more correct replacement could be

```
        if (lastScanDate.isPresent() && lmd <= lastScanDate.getAsLong()) {
            return;
        }
```

2022-02-02 22:19 UTC, dbessono commented on src/com/sun/javatest/TRT_TreeNode.java
> +            if (lastScanDate.isEmpty() || thisScanDate <= lastScanDate.getAsLong()) {
Likely the same thing here, the mentioned `SelectionTest` passes with
```
            if (lastScanDate.isPresent() && thisScanDate <= lastScanDate.getAsLong() ) {
                return false;
            }
```

2022-02-02 22:22 UTC, dbessono requested changes
seeing a failure of com.sun.javatest.SelectionTest regression test... inlined comments on the possible changes

2022-02-02 22:42 UTC, cushon commented on src/com/sun/javatest/TRT_TreeNode.java
> +        if (lastScanDate.isEmpty() || lmd <= lastScanDate.getAsLong()) {
Thanks for the catch, I have implemented the suggested fix and verified the test is now passing

2022-02-02 22:42 UTC, cushon commented on src/com/sun/javatest/TRT_TreeNode.java
> +            if (lastScanDate.isEmpty() || thisScanDate <= lastScanDate.getAsLong()) {
Done

2022-02-03 14:49 UTC, dbessono approved these changes

2022-02-03 14:50 UTC, dbessono commented on src/com/sun/javatest/TRT_TreeNode.java
> +        if (lastScanDate.isEmpty() || lmd <= lastScanDate.getAsLong()) {
thank you

2022-02-03 14:50 UTC, dbessono approved these changes

2022-02-03 18:12 UTC, cushon commented
/integrate

2022-02-03 19:45 UTC, dbessono commented
/sponsor

2022-02-03 19:46 UTC, closed without merging