7903118: Sanity Tests - Adding four JavaTest GUI newly automated sanity test scripts
openjdk/jtharness pull request #24
Opened 2022-03-07 16:16 UTC by gollayadav

Adding below automated JavaTest GUI Sanity Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine.

1.Test_Config_Edit3.java
2.Test_Config_Load1.java
3.Test_Config_New1.java
4. Test_Config_Save2.java

2022-03-11 01:18 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Config_SaveEdit/Config_SaveEdit.java
> +public class Config_SaveEdit extends ConfigTools {
What is the purpose of this class ?

2022-03-11 01:24 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Sanity_Tests/Test_Config_Edit3.java
> +    @SuppressWarnings("deprecation")
Is this done to suppress the warning about deprecated "createWorkDirInTemp" ? "createWorkDirInTemp" is used widely and it seems only in this pack of tests its usage is accompanied with '@SuppressWarnings("deprecation")'. Why is it deprecated? Should it be kept deprecated?

2022-03-11 01:26 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Sanity_Tests/Test_Config_Edit3.java
> +    @SuppressWarnings("deprecation")
Or possibly some other - non-deprecated method should be used instead of using a deprecating one and adding "@SuppressWarnings("deprecation")" ?

2022-03-11 01:35 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Sanity_Tests/Test_Config_Edit3.java
> +     *                                   runtime.
What is the idea of copying here a very general description of each exception?

2022-03-24 20:59 UTC, gollayadav commented on gui-tests/src/gui/src/jthtest/Config_SaveEdit/Config_SaveEdit.java
> +public class Config_SaveEdit extends ConfigTools {
Thanks for checking. I think this class is not required and I have removed it.

2022-03-24 21:22 UTC, gollayadav commented on gui-tests/src/gui/src/jthtest/Sanity_Tests/Test_Config_Edit3.java
> +     *                                   runtime.
Thanks for reviewing. I think this general description is not required and I have removed this general description for each exception of all the tests in PR.

2022-03-24 21:49 UTC, gollayadav commented on gui-tests/src/gui/src/jthtest/Sanity_Tests/Test_Config_Edit3.java
> +    @SuppressWarnings("deprecation")
Thanks for reviewing. I will try to use the non-deprecated method and let you know.

2022-03-25 15:34 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Config_SaveEdit/Config_SaveEdit.java
> +public class Config_SaveEdit extends ConfigTools {
thanks, looks good

2022-03-25 15:42 UTC, dbessono requested changes
With the latest changes Test_Config_Load1.java and Test_Config_Save2.java look not compilable any more.

2022-03-26 19:35 UTC, gollayadav commented
> With the latest changes Test_Config_Load1.java and Test_Config_Save2.java look not compilable any more.

Sorry for the inconvenience caused. I have corrected the compilation errors now. Could you please check.

2022-03-27 12:54 UTC, dbessono approved these changes
Looks good, thanks

2022-03-27 17:35 UTC, gollayadav commented
/integrate

2022-03-27 19:39 UTC, dbessono commented
/sponsor

2022-03-27 19:40 UTC, closed without merging