7903177: Feature Tests - Adding five JavaTest GUI legacy automated feature test scripts
openjdk/jtharness pull request #29
Opened 2022-05-03 21:19 UTC by gollayadav

Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine.

1.Config_Load5.java
2.Config_Load6.java
3.Config_LoadEdit1.java
4.Config_LoadEdit2.java
5.Config_LoadEdit3.java

2022-05-19 15:48 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Config_LoadEdit/Config_LoadEdit.java
> + */
This looks not correct. Instead it would be better to have a short description of what the test is doing.

2022-05-19 15:49 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Config_LoadEdit/Config_LoadEdit1.java
> +     * @throws NoSuchMethodException
Please remove this

2022-05-19 18:23 UTC, gollayadav commented
Thank You for your time in reviewing. I have updated/modified the scripts as per the review comments. Could you please check.

2022-05-19 21:23 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Config_LoadEdit/Config_LoadEdit.java
> +}
During the first iteration missed that this test is empty. It it really needed at all?

2022-05-19 21:23 UTC, dbessono approved these changes

2022-05-20 11:20 UTC, dbessono requested changes
What is the purpose of this test?

```
/**
 *This tests verifies the load button under configuration editor
 */
public class Config_LoadEdit extends ConfigTools {

}
```

2022-05-20 12:06 UTC, gollayadav commented on gui-tests/src/gui/src/jthtest/Config_LoadEdit/Config_LoadEdit.java
> +}
This empty test script is not required and removing it.

2022-05-20 12:40 UTC, dbessono approved these changes
Thank you for the updates, looking good

2022-05-20 12:43 UTC, gollayadav commented
/integrate

2022-05-20 12:43 UTC, dbessono commented
/sponsor

2022-05-20 12:46 UTC, closed without merging