7903375: Feature Tests - Adding five JavaTest GUI legacy automated test scripts
openjdk/jtharness pull request #42
Opened 2022-10-22 21:35 UTC by gollayadav

Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine. Also verified with JDK8 on macos.

1.Markers4.java
2.Markers5.java
3.Markers6.java
4.Markers7.java
5.Markers8.java

2022-10-31 14:56 UTC, dbessono requested changes
The code submitted for review does not compile.

2022-11-03 18:29 UTC, gollayadav commented
> The code submitted for review does not compile.

Thank You for your time in reviewing the test scripts.

Just wanted to inform you that PR#42 depends on PR#41 because 'Markers5.java' extends the 'Markers.java' class which is not available in this PR#42.

The 'Markers.java' class file is available in PR#41 (https://github.com/openjdk/jtharness/pull/41/files#diff-cf61c9cad5244549526a734335a34b38b9d3cba4b2e3a59f2015941c5a8bcb02)

Requesting you to please review PR#41 first and then PR#42, so that compile errors will not be seen.

I hope it is clear now.

2022-11-03 20:10 UTC, dbessono commented
A general request for any PR v.s. JTHarness - please make sure that it's buildable and ready for integration without any special hacking.

2022-11-10 05:28 UTC, gollayadav commented
> A general request for any PR v.s. JTHarness - please make sure that it's buildable and ready for integration without any special hacking.

Thank you for your time in reviewing the test scripts. 
In future, I will make sure this doesn't happen again.

2022-11-10 11:50 UTC, gollayadav commented
I have done the changes as suggested. Could you please check once.

2022-11-10 21:22 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Markers/Markers4.java
> + */
Please move this class description to the class declaration. Same comment for other classes,

2022-11-11 14:07 UTC, gollayadav commented on gui-tests/src/gui/src/jthtest/Markers/Markers4.java
> + */
> Please move this class description to the class declaration. Same comment for other classes,

Changes are available now. Can you please check in once.

2022-11-11 18:04 UTC, dbessono approved these changes
looks good, thanks for the updates

2022-11-22 08:14 UTC, gollayadav commented
> looks good, thanks for the updates

Thanks much for your time in reviewing the test scripts.

2022-11-22 08:15 UTC, gollayadav commented
/integrate

2022-11-23 18:16 UTC, dbessono commented
/sponsor

2022-11-23 18:18 UTC, closed without merging