7903376: Feature Tests - Adding five JavaTest GUI legacy automated test scripts
openjdk/jtharness pull request #43
Opened 2022-10-24 20:13 UTC by gollayadav

Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine. Also verified with JDK8 on macOS.

1.Markers9.java
2.Markers10.java
3.Markers11.java
4.Markers12.java
5.Markers13.java

2022-10-31 14:54 UTC, dbessono requested changes
When submitting a PR please make sure that the proposed code is buildable. This is not the case for this PR.

2022-11-03 18:42 UTC, gollayadav commented
> When submitting a PR please make sure that the proposed code is buildable. This is not the case for this PR.

Thank You so much for your time in reviewing the test scripts and sorry for the inconvenience caused. 

Just wanted to inform you that PR#43 also depends on PR#41 because 'Markers11.java' extends the 'Markers.java' class which is not available in this PR#43.

The 'Markers.java' class file is available in PR#41 (https://github.com/openjdk/jtharness/pull/41/files#diff-cf61c9cad5244549526a734335a34b38b9d3cba4b2e3a59f2015941c5a8bcb02)

Requesting you to please review PR#41 and integrate it first (OR) copy the 'Markers.java' file from PR#41 to your local workspace and start building, so that compile errors will not be seen.

I hope it is clear now. Please let me know in case of any issues.

2022-11-10 21:45 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Markers/Markers10.java
> + */
Please move this down to class declaration, here and in other sources.

2022-11-10 21:46 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Markers/Markers11.java
> +public class Markers11 extends Markers {
this deserves to be changed to static imports usage

2023-02-22 10:50 UTC, gollayadav commented
@dbessono Thank you for reviewing the test scripts. I have updated the test scripts as suggested. Could you please look into it.

2023-10-06 06:50 UTC, gollayadav commented
Closing this pull request to avoid the confusion. I will create a fresh PR and submit for review.

2023-10-06 06:50 UTC, closed without merging