7903432: Feature Tests - Adding five Java Test GUI legacy automated test scripts
openjdk/jtharness pull request #44
Opened 2023-02-13 04:39 UTC by gollayadav

Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine. Also verified with JDK8 on macOS.

1.Markers14.java
2.Markers15.java
3.Markers16.java
4.Markers17.java
5.Markers18.java

2023-02-20 13:36 UTC, dbessono commented
Please correct all class-level javadoc comments.

2023-02-20 13:36 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Markers/Markers14.java
> +        int[] indexes = new int[] { 4, 5, 6, 8, 9 };
Is this kept here intentionally? Seems not used.

2023-02-20 13:39 UTC, dbessono requested changes
Please correct all class-level javadoc comments.

2023-02-22 09:11 UTC, gollayadav commented on gui-tests/src/gui/src/jthtest/Markers/Markers14.java
> +        int[] indexes = new int[] { 4, 5, 6, 8, 9 };
@dbessono Thank you for reviewing. I have updated the test script now. Could you please check.

2023-02-22 09:21 UTC, gollayadav commented
> Please correct all class-level javadoc comments.

I have corrected the javadoc comments in all the test scripts. Could you please look into it.

2023-02-28 00:07 UTC, dbessono approved these changes
Thank you for the updates. Look good

2023-02-28 05:19 UTC, gollayadav commented
/integrate

2023-02-28 14:29 UTC, dbessono commented
/sponsor

2023-02-28 14:30 UTC, closed without merging