7903438: Feature Tests - Adding five JavaTest GUI legacy automated test scripts
openjdk/jtharness pull request #45
Opened 2023-02-18 08:29 UTC by gollayadav

Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine. Also verified with JDK8 on macOS.

1.Markers19.java
2.Markers20.java
3.ViewFilter3.java
4.ViewFilter4.java
5.ViewFilter5.java

2023-02-20 13:39 UTC, dbessono requested changes
Please correct all class-level javadoc comments.

2023-02-20 13:45 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/ViewFilter/ViewFilter2.java
> +    public void testViewFilter2() throws InterruptedException, ClassNotFoundException, InvocationTargetException, NoSuchMethodException {
InterruptedException is not thrown from the method's code.

2023-02-22 09:46 UTC, gollayadav commented on gui-tests/src/gui/src/jthtest/ViewFilter/ViewFilter2.java
> +    public void testViewFilter2() throws InterruptedException, ClassNotFoundException, InvocationTargetException, NoSuchMethodException {
@dbessono Thank you for reviewing. I have updated the test scripts. Could you please look into it.

2023-02-22 09:47 UTC, gollayadav commented
> Please correct all class-level javadoc comments.

Thank you for reviewing. Updated the javadoc comments in the test scripts. Could you please look into it.

2023-03-08 14:00 UTC, dbessono approved these changes
The tests look good, made a quick check - they pass. Thank you for contribution

2023-03-09 05:30 UTC, gollayadav commented
/integrate

2023-03-09 13:48 UTC, dbessono commented
/sponsor

2023-03-09 13:49 UTC, closed without merging