crashonly extension for jtharness - for fastdebug testing
openjdk/jtharness pull request #49
Opened 2023-08-07 13:16 UTC by andrlos

fastdebug jvm build testing is about finding out whether the jvm crashes or not... This means we are only interested in crashes and not regular failures when testing fastdebug jvms. This results in this PR that adds "crashonly" atribute for this exact case to jtharness default test runner. 
The intention is to get this addition to work with jtreg without breaking any other jtharness functionality.

2023-08-15 14:27 UTC, judovana commented on src/com/sun/javatest/DefaultTestRunner.java
> +    private boolean didCrash(TestDescription td){
To keep the conventions, maybe `isCrashed` is better?

2023-08-15 14:29 UTC, judovana commented on src/com/sun/javatest/DefaultTestRunner.java
> +        return Arrays.stream(td.getDir().list()).anyMatch(pattern.asPredicate());
Maybe it would be nice to return all found hs_err pids,  instead of just boolean  (so false would be an empty list)
Future processor very likely would like to print the hs_err files out? At least truncated?

2023-08-15 15:10 UTC, andrlos commented on src/com/sun/javatest/DefaultTestRunner.java
> +    private boolean didCrash(TestDescription td){
well the test already ran and therefore I thought that it already did/didn't crash in the time this method  has been called

2023-08-15 15:11 UTC, andrlos commented on src/com/sun/javatest/DefaultTestRunner.java
> +        return Arrays.stream(td.getDir().list()).anyMatch(pattern.asPredicate());
hmm ok, good suggestion

2023-08-15 16:18 UTC, judovana commented on src/com/sun/javatest/DefaultTestRunner.java
> +                if(result.getStatus().getType() == Status.PASSED){
Maybe such result should be skipped? Maybe it shcould be configurable whether such test should be conisedered as skipped or passed?

2023-08-15 19:32 UTC, andrlos commented on src/com/sun/javatest/DefaultTestRunner.java
> +                if(result.getStatus().getType() == Status.PASSED){
@judovana I am not aware of any mechanic that would be doing such a thing as configure the behaviour of individual test results already, therefore there would have to be a new mechanic in place that would take care of sending the argument from jtreg to jtharness eventually.. I am generally ok with marking these regularly failed tests as skipped and if anyone would want to make it configurable to switch between the SKIPPED & PASSED, then be my guest, however for the usecase of the enhancement and testing fastdebug jvms, this should be more than sufficient.

2023-08-15 19:33 UTC, andrlos commented on src/com/sun/javatest/DefaultTestRunner.java
> +        return Arrays.stream(td.getDir().list()).anyMatch(pattern.asPredicate());
I will redo this part and there will be another function getCrashes that will return list of pids and hserr txt contents in crash objects and the function didCrash will only check whether the list is empty or not.
Thanks for the suggestion.

2023-08-16 07:46 UTC, judovana commented on src/com/sun/javatest/DefaultTestRunner.java
> +                if(result.getStatus().getType() == Status.PASSED){
Maybe.. :) Up to you. To make the --crashes to take parameter would not be that hard.  Eg --crashOnly[=passed] or --crashOnly=ignored...

Buy  you are right, there may be many of similar tweaks, so  rather keep the --crashOnly simple, and add config later.

2023-08-16 07:53 UTC, judovana commented on src/com/sun/javatest/interview/BasicInterviewParameters.java
> +    public boolean getCrashOnly() {
isCrashOnly if it is boolean, it is always is.

2023-08-16 07:57 UTC, judovana commented on src/com/sun/javatest/interview/BasicInterviewParameters.java
> +    private boolean crashOnly;
Is there any particula reason why the variable is declared on the bottom, and not with others?

2023-08-16 08:00 UTC, dbessono requested changes
Assuming this is an extension the suggestion is to not modify the DefaultTestRunner, Harness, etc. and the core classes

2023-08-21 10:32 UTC, andrlos commented
@dbessono just for clarification this was intended more like an enhancement not an extension and I tried to do it the most direct and simple way possible... however I can try to rework it as an extension, where I can overload each of the used classes and just use them in jtreg in a similar manner to how it works now... what do you think of this approach and can you please just glance at the https://github.com/openjdk/jtreg/pull/164 and tell me if this modification of jtreg code is ok or needs to be rewritten as well? Thanks!

2023-08-27 18:56 UTC, andrlos commented
@dbessono I am not sure that what I proposed in my previous comment is possible without a serious rework of a considerable part of the jtreg project.. since there is basically only one class that is responsible for communication between jtreg and jtharness and that is RegressionParameters that directly extends BasicInterviewParameters. If I don't at least modify BasicInterviewParameters (probably the interface Parameters would have to be touched a bit too) in jtharness, than the extension you are proposing would mean rewriting half of the code responsible for communication between jtreg & jtharness. Thoughts?
I am still convinced that the presented code in this PR is the most minimalistic and simple solution to the https://bugs.openjdk.org/browse/CODETOOLS-7903519

2023-08-30 16:04 UTC, andrlos commented
@dbessono 
so basically what you are saying is that nothing like this will be allowed into the jtharness by you even if I dont touch the core classes

2023-08-30 16:20 UTC, dbessono commented
> @dbessono so basically what you are saying is that nothing like this will be allowed into the jtharness by you even if I dont touch the core classes

We should keep a balance between generic functionality residing in the basic default implementations, and various extensions. It might be even OK to have such extension as part of the JTHarness codebase, but that depends on how everything is organized and layered.

2023-08-30 16:58 UTC, andrlos commented
@dbessono so if I just extend the core classes without touching them - that might be allowed to the codebase?

2023-09-04 14:09 UTC, andrlos commented
@dbessono, I created a clone of current master and melded a new approach of doing this into it, it can be seen in this PR into my fork (did not want to create hundreds of PRs here) please take a look if this would be acceptable.. I had to touch the core classes a little bit to separate some mechanics that would otherwise force me to copypaste really huge methods.. https://github.com/andrlos/jtharness/pull/1 Thanks for taking a look :-)

2023-09-18 11:19 UTC, dbessono requested changes
Kindly requesting to update this PR to keep the change iterations here, or to open a new one for jtharness project

2023-09-29 22:15 UTC, closed without merging

2023-09-29 22:15 UTC, andrlos commented
the commit history here got out of hand.. closing MR and creating a new one with clearer history for this will be easier