exracting method to fill in result status to allow for overriding in implementations of Script
openjdk/jtharness pull request #59
Opened 2024-01-09 20:43 UTC by andrlos

This is an alternative approach to https://github.com/openjdk/jtharness/pull/57
counting on Script subclasses that will allow for such modifications.

2024-01-10 07:49 UTC, judovana commented on src/com/sun/javatest/Script.java
> +    protected void fillTestExecutionStatus(TestResult testResultToFill, Status execStatus) {
I would  suggest `setTestResultStatus` or `modifyTestResultStatus`, as we are dealing with testResult variable ; or `setTestRunStatus` or `modifyTestRuntStatus` as we are called in `run`. But you know better, just ideas from point of view what I would be searching in autocompletion (fill is unlikely, execution more likely, still  rare)

2024-01-10 13:58 UTC, andrlos commented on src/com/sun/javatest/Script.java
> +    protected void fillTestExecutionStatus(TestResult testResultToFill, Status execStatus) {
well I would vote the "modify" based names out, since by default this wont be changing anything..

2024-01-10 13:59 UTC, andrlos commented on src/com/sun/javatest/Script.java
> +    protected void fillTestExecutionStatus(TestResult testResultToFill, Status execStatus) {
I went with the naming kindly provided by @dbessono but I am happy to change it however we agree.

2024-01-11 08:35 UTC, judovana commented on src/com/sun/javatest/Script.java
> +    protected void fillTestExecutionStatus(TestResult testResultToFill, Status execStatus) {
> well I would vote the "modify" based names out, since by default this wont be changing anything..
but htat is the reason of the method, isnt it?

2024-01-11 22:38 UTC, andrlos commented
/integrate

2024-02-26 12:13 UTC, dbessono commented on src/com/sun/javatest/Script.java
> +    protected void fillTestExecutionStatus(TestResult testResultToFill, Status execStatus) {
Agree, `setTestResultStatus` looks more simple and clear, taking into account the default implementation especially ...

2024-02-26 12:15 UTC, dbessono requested changes
<!-- Start of TOU acceptance message header -->
Hi @dbessono, thanks for making a comment in an OpenJDK project!

All comments and discussions in the OpenJDK Community must be made available under the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/). If you already are an OpenJDK [Author](https://openjdk.java.net/bylaws#author), [Committer](https://openjdk.java.net/bylaws#committer) or [Reviewer](https://openjdk.java.net/bylaws#reviewer), please click [here](https://bugs.openjdk.java.net/secure/CreateIssue.jspa?pid=11300&issuetype=1) to open a new issue so that we can record that fact. Please Use "Add GitHub user dbessono" for the summary.

If you are not an OpenJDK Author, Committer or Reviewer, simply check the box below to accept the OpenJDK Terms of Use for your comments.
<!-- End of TOU acceptance message header -->
 - [ ]  I agree to the [OpenJDK Terms of Use](https://openjdk.java.net/legal/tou/) for all comments I make in a project in the [OpenJDK GitHub organization](https://github.com/openjdk).
<!-- Start of TOU acceptance message footer -->
Your comment will be automatically restored once you have accepted the OpenJDK [Terms of Use](https://openjdk.java.net/legal/tou/).
<!-- End of TOU acceptance message footer -->
<!-- Original message to be restored:
The+change+looks+simple+and+safe%2C+just+the+name+of+the+method+could+be+simplified+indeed+...
-->

2024-05-29 05:04 UTC, andrlos commented
/open

2024-05-29 13:17 UTC, andrlos commented
/integrate

2024-06-18 09:50 UTC, andrlos commented
@dbessono I edited the name of the method, can you take a look please?

2024-06-21 12:51 UTC, dbessono commented
> @dbessono I edited the name of the method, can you take a look please?

Thank you for the update, looks good.

2024-06-21 12:52 UTC, dbessono approved these changes

2024-06-25 11:13 UTC, andrlos commented
@dbessono can you sponsor please? I don't have the rights.

2024-06-25 11:24 UTC, dbessono commented
/sponsor

2024-06-25 11:26 UTC, closed without merging