7903718: Feature Tests - Adding four JavaTest GUI legacy automated test scripts
openjdk/jtharness pull request #71
Opened 2024-04-22 10:35 UTC by gollayadav

Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine. Also verified with JDK8 on macos.

1. Markers22.java
2. ReportConverter1.java
3. View2.java
4. View3.java

2024-05-20 12:32 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Markers/Markers22.java
> +          return "Start JavaTest with the -NewDesktop option. Create a workdirectory. Load an existing JTI file. Bring up configuration editor by doing Ctrl-E. Select the Enable Bookmarks from the Bo
Please split into several lines

2024-06-14 04:04 UTC, gollayadav commented on gui-tests/src/gui/src/jthtest/Markers/Markers22.java
> +          return "Start JavaTest with the -NewDesktop option. Create a workdirectory. Load an existing JTI file. Bring up configuration editor by doing Ctrl-E. Select the Enable Bookmarks from the Bo
I have already mentioned Test 'Description' at starting. Hence removed this extra description comment. Hope this is fine.

2024-06-14 04:16 UTC, gollayadav commented on gui-tests/src/gui/src/jthtest/StandardConfig_View/View.java
> +        }/**/
Test 'Description' is not required for this class because this is the base class. So, removed the empty comment section.
Hope this is fine.

2024-06-14 11:57 UTC, gollayadav commented
@dbessono Thank You for your time in reviewing the test scripts.
Updated the test scripts as suggested and it is ready for review. Could you please check and review the test scripts.

2024-07-16 11:34 UTC, dbessono commented on gui-tests/src/gui/src/jthtest/Markers/Markers22.java
> +          return "Start JavaTest with the -NewDesktop option. Create a workdirectory. Load an existing JTI file. Bring up configuration editor by doing Ctrl-E. Select the Enable Bookmarks from the Bo
Test description doesn't contain the text which has been deleted. Please restore description here and split into several lines.

2024-07-16 11:37 UTC, dbessono requested changes
For Markers22 the description doesn't contain the text which has been deleted. Please restore ::getDescription method and split the returned value into several lines to have it more readable.

2025-03-19 15:31 UTC, gollayadav commented
/open

2025-05-14 18:01 UTC, closed without merging